version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Nginx in the frontend container will serve on port 80
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src # Mount src for development, remove for production
      # The following volume is to ensure that node_modules is not overwritten by the host
      # if it exists, especially during development.
      - /app/node_modules

networks:
  default:
    name: web_network
